config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :new, :destroy]

  resources :users, only: [:new, :show, :create]

  resources :posts, except: [:index, :new] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: :show

  root "subs#index"

  resources :subs do
    resources :posts, only: [:new]
  end

  post 'posts/:id/upvote', to: 'posts#upvote', as: :post_upvote
  post 'comments/:id/upvote', to: 'comments#upvote', as: :comment_upvote

  post 'posts/:id/downvote', to: 'posts#downvote', as: :post_downvote
  post 'comments/:id/downvote', to: 'comments#downvote', as: :comment_downvote

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    primary_key: :id,
    class_name: :User

  has_many :post_subs,
    dependent: :destroy

  has_many :posts,
    through: :post_subs,
    source: :post
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :is_moderator, only: [:update, :edit, :destroy]

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def new

  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def is_moderator
    @sub = Sub.find(params[:id])
    
    unless @sub.moderator == current_user
      flash[:errors] = ["Not permitted"]
      redirect_to sub_url(@sub)
    end
  end

end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
<h1>Edit sub</h1>

<form class="" action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label for="title">Title:</label>
  <input id="title" type="text" name="sub[title]" value="<%= @sub.title %>">

  <label for="description">Description:</label>
  <textarea id="description" name="sub[description]" rows="8" cols="80">
    <%= @sub.description %>
  </textarea>

  <input type="submit" name="" value="Edit sub">
</form>
  <%= button_to 'Delete sub', sub_url(@sub), method: :delete %>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <li> <%= link_to sub.title, sub_url(sub) %> </li>
  <% end %>
</ul>

<%= link_to 'Add sub', new_sub_url %>

app/views/subs/new.html.erb
<h1>Add new sub</h1>

<form class="" action="<%= subs_url %>" method="post">
  <%= auth_token %>

  <label for="title">Title:</label>
  <input id="title" type="text" name="sub[title]" value="">

  <br>

  <label for="description">Description:</label>
  <br>
  <textarea id="description" name="sub[description]" rows="8" cols="80"></textarea>

  <br>

  <input type="submit" name="" value="Add sub">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<p> <%= @sub.description %></p>


<ul>
<% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %></li>
<% end %>
</ul>

<br>
<% if current_user %>
  <%= link_to "Add Post", new_sub_post_url(@sub) %>
<% end %>

<br>
<br>
<% if current_user == @sub.moderator %>
  <%= link_to "Edit sub", edit_sub_url(@sub) %>
<% end %>
<br>
<%= link_to 'Back to index', root_url %>