config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :new, :destroy]

  resources :users, only: [:new, :show, :create]

  resources :posts, except: [:index, :new] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: :show

  root "subs#index"

  resources :subs do
    resources :posts, only: [:new]
  end

  post 'posts/:id/upvote', to: 'posts#upvote', as: :post_upvote
  post 'comments/:id/upvote', to: 'comments#upvote', as: :comment_upvote

  post 'posts/:id/downvote', to: 'posts#downvote', as: :post_downvote
  post 'comments/:id/downvote', to: 'comments#downvote', as: :comment_downvote

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author_id, presence: true

  has_one :moderator,
    through: :sub,
    source: :moderator

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs,
    dependent: :destroy

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments,
    dependent: :destroy

  has_many :votes, as: :votable

  def comments_by_parent_id
    hash = Hash.new { |h, k| h[k] = [] }
    Comment.where(post_id: self.id).each do |comment|
      hash[comment.parent_id] << comment
    end
    hash
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :is_author_or_mod, only: [:update, :edit, :destroy]

  def show
    @post = Post.find(params[:id])
    @all_comments = @post.comments_by_parent_id
    @votes = Vote.where(votable_id: params[:id], votable_type: Post).sum(:value)
  end

  def new
    @subs = Sub.all
  end

  def create
    @subs = Sub.all
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save!
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @subs = Sub.all
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_url
  end

  def upvote
    @post = Post.find(params[:id])
    Vote.create(value: 1, votable_id: @post.id, votable_type: Post)

    redirect_to post_url(@post)
  end

  def downvote
    @post = Post.find(params[:id])
    Vote.create(value: -1, votable_id: @post.id, votable_type: Post)

    redirect_to post_url(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def is_author_or_mod
    @post = Post.find(params[:id])
    unless current_user == @post.author || current_user == @post.moderator
      flash[:errors] = ["Not permitted"]
      redirect_to post_url(@post)
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="_method" value="patch">

  <label for="title">Title:</label>
  <input type="text" name="post[title]" id="title" value="<%= @post.title %>">
  <br>

  <label for="url">URL:</label>
  <input type="text" name="post[url]" id="url" value="<%= @post.url %>">
  <br>

  <label for="content">Content:</label><br>
  <textarea name="post[content]" rows="8" cols="80" id="content"><%= @post.content %></textarea>
  <br>

  <label>Subreddits:</label><br>
  <% @subs.each do |sub| %>
    <label>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <%= "checked" if @post.subs.include?(sub)  %> >
      <%= sub.title %>
    </label><br>
  <% end %>
  <br>

  <input type="submit" value="Edit Post">

</form>

<%= button_to "Delete Post", post_url(@post), method: :delete %>

app/views/posts/new.html.erb
<h1>Create a post</h1>

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>

  <label for="title">Title:</label>
  <input type="text" name="post[title]" id="title">
  <br>

  <label for="url">URL:</label>
  <input type="text" name="post[url]" id="url">
  <br>

  <label for="content">Content:</label><br>
  <textarea name="post[content]" rows="8" cols="80" id="content"></textarea>
  <br>



  <label>Subreddits:</label><br>
  <% @subs.each do |sub| %>
    <label>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <%= "checked" if sub.id == params[:sub_id].to_i %> >
      <%= sub.title %>
    </label><br>
  <% end %>
  <br>

  <input type="submit" value="Save Post">

</form>

<br>

<%= link_to "Back to index", root_url %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>Score: <%= @votes %></p>
<%= button_to "Upvote", post_upvote_url(@post), method: :post %>
<%= button_to "Downvote", post_downvote_url(@post), method: :post %>

<% unless @post.url == "" %>
  <%= link_to "URL", @post.url %>
<% end %>

<br>

<p><%= @post.content %></p>
<br>
<% if current_user == @post.author || current_user == @post.moderator %>
  <%= link_to "Edit Post", edit_post_url(@post) %>
<% end %>

<br><br>

<% @post.subs.each do |sub| %>
  <%= link_to "Back to #{sub.title}", sub_url(sub) %><br>
<% end %>

<br>
  <%= link_to "Add comment", new_post_comment_url(@post) %>
<br>

<% @all_comments[nil].each do |comment| %>
  <h4>User: <%= comment.author.username %></h4>

  <p>Score: <%= comment.votes.sum(:value) %></p>
  <%= button_to "Upvote", comment_upvote_url(comment), method: :post %>
  <%= button_to "Downvote", comment_downvote_url(comment), method: :post %>

  <p><%= comment.content %></p>
  <p>Posted at:<%= comment.created_at %></p>
  <%= render "layouts/comment", comment: comment, all_comments: @all_comments %>
<% end %>