config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :new, :destroy]

  resources :users, only: [:new, :show, :create]

  resources :posts, except: [:index, :new] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: :show

  root "subs#index"

  resources :subs do
    resources :posts, only: [:new]
  end

  post 'posts/:id/upvote', to: 'posts#upvote', as: :post_upvote
  post 'comments/:id/upvote', to: 'comments#upvote', as: :comment_upvote

  post 'posts/:id/downvote', to: 'posts#downvote', as: :post_downvote
  post 'comments/:id/downvote', to: 'comments#downvote', as: :comment_downvote

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_comment.html.erb
<form class="" action="<%= post_comments_url(comment.post_id) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[parent_id]" value="<%= comment.id %>">

  <label for="content">Content:</label><br>
  <textarea id="content" name="comment[content]" rows="4" cols="40"></textarea><br>

  <input type="submit" name="" value="Add comment">

</form>

<% all_comments[comment.id].each do |child_comment| %>
  <ul><h4>User: <%= child_comment.author.username %></h4>

  <p>Score: <%= comment.votes.sum(:value) %></p>
  <%= button_to "Upvote", comment_upvote_url(comment), method: :post %>
  <%= button_to "Downvote", comment_downvote_url(comment), method: :post %>

  <p><%= child_comment.content %></p>
  <p>Posted at:<%= child_comment.created_at %></p>
  <%= render "layouts/comment", comment: child_comment, all_comments: all_comments %></ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <% if current_user %>
        <%= button_to "Log out", session_url(current_user), method: :delete %>
      <% else %>
        <%= link_to "Log in", new_session_url %>
        <%= link_to "Register", new_user_url %>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>